// Communication Menu
// Defines custom comm menu entries for the template
// TEMPLATE SPECIFIC FUNCTIONS. DO NOT EDIT THIS FILE DIRECTLY UNLESS YOU KNOW WHAT YOU'RE DOING!

class xpt_jipTeleport	// Activates the JIP teleporter.
{
	text = "Teleport to Squad";
	submenu = "";
	expression = "";
	icon = "";
	cursor = "";
	enable = "alive player";
	removeAfterExpressionCall = 0;
};