// CfgDebriefingSections.hpp
// Defines custom "debriefing sections". These can be used to display additional information at the end of a mission.
// TEMPLATE SPECIFIC FUNCTIONS. DO NOT EDIT THIS FILE DIRECTLY UNLESS YOU KNOW WHAT YOU'RE DOING!

// Nothing here (for now)