// Functions library
// Defines custom functions for the template.
// TEMPLATE SPECIFIC FUNCTIONS. DO NOT EDIT THIS FILE DIRECTLY UNLESS YOU KNOW WHAT YOU'RE DOING!

// Template functions now use the XPT tag to differentiate them from functions I write myself. --Superxpdude
class XPT
{
	class debug
	{
		file = "template\functions\debug";
		class errorReport {}; // Function for handling error reporting
	};
};