// Functions library
// Defines custom functions for the template.
// TEMPLATE SPECIFIC FUNCTIONS. DO NOT EDIT THIS FILE DIRECTLY UNLESS YOU KNOW WHAT YOU'RE DOING!

// Template functions now use the XPT tag to differentiate them from functions I write for my own missions. --Superxpdude
class XPT
{
	class curator
	{
		file = "template\functions\curator";
		class curatorAddUnit {}; // Function to add an editable unit to all curators
		class curatorEH {postInit = 1}; // Function for adding event handlers to curators on mission start
		class curatorGrpPlaced {}; // Function for adding curator placed groups to other curators
		class curatorObjPlaced {}; // Function for adding curator placed objects to other curators
		class curatorRemoveNVG {}; // Function for removing NVGs from curator-spawned units
	};
	class debug
	{
		file = "template\functions\debug";
		class errorReport {}; // Function for handling error reporting
	};
	class headlessClient
	{
		file = "template\functions\headlessClient";
		class headlessConnect {}; // Function for handling the headlessClient connecting
		class headlessDisconnect {}; // Function for handling the headlessClient disconnecting
		class headlessSetGroupOwner {}; // Function for moving groups to the headlessClient
		class headlessSetup {preInit = 1}; // Function for setting up the headlessClient framework
	};
	class loadout
	{
		file = "template\functions\loadout";
		class loadInventory {}; // Function for loading a unit's inventory
	};
	class radio
	{
		file = "template\functions\radio";
		class setupTFAR {preInit = 1}; // Function for configuring radio settings
	};
	class system
	{
		file = "template\functions\system"
	};
};