// Notifications system
// Notifications for the template
// TEMPLATE SPECIFIC PARAMETERS. DO NOT EDIT THIS FILE DIRECTLY UNLESS YOU KNOW WHAT YOU'RE DOING!

class XPT_debugMode // Debug mode notification. Displays when a mission is started with debug mode enabled.
{
	title = "Debug Mode";
	iconPicture = "";
	iconText = "";
	description = "Debug mode is enabled. Some mission parameters may be changed.";
	duration = 10;
	priority = 100000;
};