// Mission parameters
// Available in mission lobby
// TEMPLATE SPECIFIC PARAMETERS. DO NOT EDIT THIS FILE DIRECTLY UNLESS YOU KNOW WHAT YOU'RE DOING!
class header_ace_medical
{
	title = "===== ACE3 - Medical Settings =====";
	values[] = {0};
	texts[] = {""};
	default = 0;
};
class ace_medical_level
{
	title = "ACE3 - Medical Level";
	ACE_setting = 1;
	values[] = {1,2};
	texts[] = {"Basic", "Advanced"};
	default = XPT_DEFAULTMEDICAL;
};
class ace_medical_preventInstaDeath
{
	title = "ACE3 - Prevent Instant Death";
	ACE_setting = 1;
	values[] = {0,1};
	texts[] = {"Disabled", "Enabled"};
	#ifdef XPT_DEFINEPVP
		default = 0;
	#else
		default = 1;
	#endif
};
class ace_medical_enableRevive
{
	title = "ACE3 - Enable Revive";
	ACE_setting = 1;
	values[] = {0,1};
	texts[] = {"Disabled", "Enabled"};
	#ifdef XPT_DEFINEPVP
		default = 0;
	#else
		default = 1;
	#endif
};
class ace_medical_maxReviveTime
{
	title = "ACE3 - Revive Bleedout Timer";
	ACE_setting = 1;
	values[] = {30,60,90,120,180,240,300};
	texts[] = {"30 seconds", "60 seconds", "90 seconds", "2 minutes", "3 minutes", "4 minutes", "5 minutes"};
	default = 300;
};
class ace_medical_enableUnconsciousnessAI
{
	title = "ACE3 - AI Unconsciousness";
	ACE_setting = 1;
	values[] = {0,1,2};
	texts[] = {"Disabled", "50/50", "Enabled"};
	default = 0;
};
class header_mission_settings
{
	title = "===== Template Settings =====";
	values[] = {0};
	texts[] = {""};
	default = 0;
};
class XPT_map_markers
{
	title = "XPT - Enable group tracking on map";
	values[] = {0,1};
	texts[] = {"Disabled", "Enabled"};
	default = XPT_DEFAULTGROUPTRACK;
	isGlobal = 0;
	function = "SXP_fnc_mapMarkers";
};
class XPT_headlessclient
{
	title = "XPT - Enable Headless Client support";
	values[] = {0,1};
	texts[] = {"Disabled", "Automatic"};
	default = 1;
	isGlobal = 0;
};
class XPT_debugMode
{
	title = "XPT - Enable debug mode";
	values[] = {0,1};
	texts[] = {"Disabled", "Enabled"};
	default = 0;
};
