// Respawn Templates
// Defines custom respawn templates for the template.
// TEMPLATE SPECIFIC FUNCTIONS. DO NOT EDIT THIS FILE DIRECTLY UNLESS YOU KNOW WHAT YOU'RE DOING!

class XPT_wave
{
	onPlayerKilled = "XPT_fnc_waveOnPlayerKilled";
};

class XPT_EGSpec
{
	onPlayerKilled = "XPT_fnc_EGSpecWithMenuRespawn";
};