// Config definitions
// Used to handle things such as default lobby param settings, and handle cases where new definitions are added, but old missions do not have them defined.
// TEMPLATE SPECIFIC DEFINITIONS. DO NOT EDIT THIS FILE DIRECTLY UNLESS YOU KNOW WHAT YOU'RE DOING!

//-------------------- Template parameter defines

// XPT map markers. Defaults to Enabled.
#ifndef XPT_MAPMARKERS
	#define XPT_MAPMARKERS 1
#endif

// XPT JIP teleporter. Defaults to Enabled.
#ifndef XPT_JIPTELEPORT
	#define XPT_JIPTELEPORT 1
#endif

// XPT safe-start. Defaults to Enabled.
#ifndef XPT_SAFESTART
	#define XPT_SAFESTART 1
#endif

// XPT debug mode. Defaults to disabled.
#ifndef XPT_DEBUGMODE
	#define XPT_DEBUGMODE 0
#endif


//-------------------- ACE 3 medical defines

// ACE 3 medical level. Defaults to basic medical.
#ifndef XPT_ACE3_MEDICALLEVEL
	#define XPT_ACE3_MEDICALLEVEL 1
#endif

// ACE 3 player damage threshold. Defaults to 100%.
#ifndef XPT_ACE3_PLAYERDAMAGETHRESHOLD
	#define XPT_ACE3_PLAYERDAMAGETHRESHOLD 1
#endif

// ACE 3 AI damage threshold. Defaults to 100%.
#ifndef XPT_ACE3_AIDAMAGETHRESHOLD
	#define XPT_ACE3_AIDAMAGETHRESHOLD 1
#endif

// ACE 3 PID for co-op missions. Defaults to Enabled.
#ifndef XPT_ACE3_PREVENTINSTANTDEATH_COOP
	#define XPT_ACE3_PREVENTINSTANTDEATH_COOP 1
#endif

// ACE 3 revive for co-op missions. Defaults to Enabled.
#ifndef XPT_ACE3_REVIVE_COOP
	#define XPT_ACE3_REVIVE_COOP 1
#endif

// ACE 3 PID for PVP missions. Defaults to Disabled.
#ifndef XPT_ACE3_PREVENTINSTANTDEATH_PVP
	#define XPT_ACE3_PREVENTINSTANTDEATH_PVP 0
#endif

// ACE 3 revive for PVP missions. Defaults to Disabled.
#ifndef XPT_ACE3_REVIVE_PVP
	#define XPT_ACE3_REVIVE_PVP 0
#endif

// ACE 3 revive timer. Defaults to 300 seconds.
#ifndef XPT_ACE3_REVIVE_TIMER
	#define XPT_ACE3_REVIVE_TIMER 300
#endif