name: XP Template
on: push

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout the source code
            uses: actions/checkout@master
          - name: Lint (sqflint)
            uses: arma-actions/sqflint@master